{% set name = "pynucastro" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynucastro-{{ version }}.tar.gz
  sha256: 601848ecb2b2424f3b5fbcf45d4e77c302673c8ba52c39250c889f36afb89a66

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.9
    - ipywidgets >=7.1.2
    - matplotlib-base >=2.1.0
    - networkx >=2.1
    - numpy >=1.13.3,<3.0
    - scipy >=1.0.0
    - sympy >=1.1.1
  run_constrained:
    - numba >=0.52

test:
  imports:
    - pynucastro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pynucastro/pynucastro
  summary: A python library for nuclear astrophysics
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zingale
    - yut23
